import type { Metadata } from "next";
import Link from "next/link";
import "./globals.css";

export const metadata: Metadata = {
  title: "The fake store shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  overlay,
}: Readonly<{
  children: React.ReactNode;
  overlay: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className=" min-h-screen ">
        <header className="flex flex-auto justify-between border-b items-center border-gray-200 px-12 py-4 bg-white">
          <div className="text-xl font-bold">The fake store shop</div>
          <Link
            href={"/basket"}
            className="cursor-pointer text-md font-bold text-gray-500"
          >
            Open Basket
          </Link>
        </header>
        {overlay}
        {children}
      </body>
    </html>
  );
}
